version: '3.8'

services:
  app:
    build:
      dockerfile: ./app.dockerfile
      context: .
    ports:
      - 80:80
      # - 443 equal to 443:443
    volumes:
      - ./app:/var/www/app
    # environment:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - dbdata:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  dbdata: